# Generated by Django 5.2.6 on 2025-10-15 20:23

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import news.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (slug)')),
                ('anons', models.TextField(blank=True, null=True, verbose_name='Анонс')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.safe_image_upload_to, verbose_name='Изображение (файл)')),
                ('image_url', models.URLField(blank=True, help_text='Добавьте URL изображения', null=True, verbose_name='URL изображения')),
                ('section', models.CharField(choices=[('main', 'Остальные новости'), ('foreign', 'Иностранная пресса')], default='main', max_length=50, verbose_name='Тип публикации')),
                ('views', models.PositiveIntegerField(default=0)),
                ('telegram_embed', models.TextField(blank=True, help_text='Код embed из Telegram', null=True, verbose_name='Embed из Telegram')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Раздел спорта')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес пользователя')),
                ('is_like', models.BooleanField(help_text='True — лайк, False — дизлайк', verbose_name='Лайк?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата голосования')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.article', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Реакция на новость',
                'verbose_name_plural': 'Реакции на новости',
                'unique_together': {('article', 'ip_address')},
            },
        ),
    ]
