# Generated by Django 5.1.1 on 2025-09-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_body_article_content_remove_article_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='telegram_embed',
            field=models.TextField(blank=True, null=True, verbose_name='Embed из Telegram'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Картинка (URL)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
