# Generated by Django 5.1.1 on 2025-09-18 17:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_telegram_embed_alter_article_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Текст статьи'),
        ),
    ]
