"""
Django settings for SportHub project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zyc!d&w@pb&1s6#@8^-^k2xo=s8o(t@trf8a*mi7m71y#%z6mf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Jazzmin должен быть ПЕРВЫМ, чтобы переопределить админ
    "jazzmin", # админка
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news',  # <-- наше приложение
    "ckeditor",  # редактор текста
    'django.contrib.humanize', # форматирует дату и время
    'django.contrib.sitemaps', # карта сайта
    'taggit', # теги
]
# Настройки Jazzmin (пример красивой конфигурации — можно править под вкус)
JAZZMIN_SETTINGS = {
    "site_title": "SportHub Admin",
    "site_header": "SportHub",
    "site_brand": "SportHub",
    # "site_logo": "news/images/logo_admin.png",  # путь в static, раскомментируй как появится логотип
    "welcome_sign": "Добро пожаловать в админку SportHub",
    "copyright": "SportHub © 2025",
    "search_model": "news.News",
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",  # приятная раскладка формы
    "language_chooser": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "news": "fas fa-newspaper",
        "news.News": "fas fa-file-lines",
        "news.Category": "fas fa-tags",
    },
    "topmenu_links": [
        {"name": "На сайт", "url": "/", "new_window": False},
        {"name": "Добавить новость", "url": "/admin/news/article/add/", "permissions": ["news.add_news"]},
    ],
}

# Небольшие UI tweeks (цвета/отступы)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_colour": "#0d6efd",  # основной цвет (Bootstrap primary)
    "accent": "accent-primary",
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SportHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'news.context_processors.categories_processor',  # 👈 наше добавление
            ],
        },
    },
]

WSGI_APPLICATION = 'SportHub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# CKEditor (загрузка файлов)
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 400,
        'width': '100%',
    },
}